import Head from 'next/head'
import Link from 'next/link'
export default function About() {
	return (
		<>
		<Head>
			<title>Create Next App - About</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<div>this is about home</div>
		<Link href="/">返回首页</Link>
		</>
	)
}